 
apiVersion: v1  
kind: Service                           # Type of the kubernetes resource
metadata:
  name: horsemaze             # Name of the Kubernetes resource
  labels:                               # Labels that will be applied to the resource
    app: horsemaze
spec:
  type: NodePort                        # Gives each node an external IP that’s accessible from outside the cluster and also opens a Port.
  selector:
    app: horsemaze            # Selects any Pod with labels `app=fullstack-app-mysql`
  ports: 
  - name: http
    port: 8050
    targetPort: 8050